# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import thread_service_pb2 as thread__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in thread_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ThreadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateThread = channel.unary_unary(
                '/threadservice.v1.ThreadService/CreateThread',
                request_serializer=thread__service__pb2.CreateThreadRequest.SerializeToString,
                response_deserializer=thread__service__pb2.CreateThreadResponse.FromString,
                _registered_method=True)
        self.AppendMessage = channel.unary_unary(
                '/threadservice.v1.ThreadService/AppendMessage',
                request_serializer=thread__service__pb2.AppendMessageRequest.SerializeToString,
                response_deserializer=thread__service__pb2.AppendMessageResponse.FromString,
                _registered_method=True)
        self.GetThread = channel.unary_unary(
                '/threadservice.v1.ThreadService/GetThread',
                request_serializer=thread__service__pb2.GetThreadRequest.SerializeToString,
                response_deserializer=thread__service__pb2.GetThreadResponse.FromString,
                _registered_method=True)
        self.ListThreads = channel.unary_unary(
                '/threadservice.v1.ThreadService/ListThreads',
                request_serializer=thread__service__pb2.ListThreadsRequest.SerializeToString,
                response_deserializer=thread__service__pb2.ListThreadsResponse.FromString,
                _registered_method=True)
        self.StreamThreadMessages = channel.unary_stream(
                '/threadservice.v1.ThreadService/StreamThreadMessages',
                request_serializer=thread__service__pb2.StreamThreadMessagesRequest.SerializeToString,
                response_deserializer=thread__service__pb2.Message.FromString,
                _registered_method=True)


class ThreadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamThreadMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ThreadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateThread': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateThread,
                    request_deserializer=thread__service__pb2.CreateThreadRequest.FromString,
                    response_serializer=thread__service__pb2.CreateThreadResponse.SerializeToString,
            ),
            'AppendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendMessage,
                    request_deserializer=thread__service__pb2.AppendMessageRequest.FromString,
                    response_serializer=thread__service__pb2.AppendMessageResponse.SerializeToString,
            ),
            'GetThread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThread,
                    request_deserializer=thread__service__pb2.GetThreadRequest.FromString,
                    response_serializer=thread__service__pb2.GetThreadResponse.SerializeToString,
            ),
            'ListThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.ListThreads,
                    request_deserializer=thread__service__pb2.ListThreadsRequest.FromString,
                    response_serializer=thread__service__pb2.ListThreadsResponse.SerializeToString,
            ),
            'StreamThreadMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamThreadMessages,
                    request_deserializer=thread__service__pb2.StreamThreadMessagesRequest.FromString,
                    response_serializer=thread__service__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'threadservice.v1.ThreadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('threadservice.v1.ThreadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ThreadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threadservice.v1.ThreadService/CreateThread',
            thread__service__pb2.CreateThreadRequest.SerializeToString,
            thread__service__pb2.CreateThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threadservice.v1.ThreadService/AppendMessage',
            thread__service__pb2.AppendMessageRequest.SerializeToString,
            thread__service__pb2.AppendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threadservice.v1.ThreadService/GetThread',
            thread__service__pb2.GetThreadRequest.SerializeToString,
            thread__service__pb2.GetThreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/threadservice.v1.ThreadService/ListThreads',
            thread__service__pb2.ListThreadsRequest.SerializeToString,
            thread__service__pb2.ListThreadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamThreadMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/threadservice.v1.ThreadService/StreamThreadMessages',
            thread__service__pb2.StreamThreadMessagesRequest.SerializeToString,
            thread__service__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
