# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import research_service_pb2 as research__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in research_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Research = channel.unary_unary(
                '/researchservice.v1.ResearchService/Research',
                request_serializer=research__service__pb2.ResearchRequest.SerializeToString,
                response_deserializer=research__service__pb2.ResearchResponse.FromString,
                _registered_method=True)
        self.ResearchStream = channel.unary_stream(
                '/researchservice.v1.ResearchService/ResearchStream',
                request_serializer=research__service__pb2.ResearchRequest.SerializeToString,
                response_deserializer=research__service__pb2.ResearchEvent.FromString,
                _registered_method=True)


class ResearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Research(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResearchStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Research': grpc.unary_unary_rpc_method_handler(
                    servicer.Research,
                    request_deserializer=research__service__pb2.ResearchRequest.FromString,
                    response_serializer=research__service__pb2.ResearchResponse.SerializeToString,
            ),
            'ResearchStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ResearchStream,
                    request_deserializer=research__service__pb2.ResearchRequest.FromString,
                    response_serializer=research__service__pb2.ResearchEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'researchservice.v1.ResearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('researchservice.v1.ResearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Research(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/researchservice.v1.ResearchService/Research',
            research__service__pb2.ResearchRequest.SerializeToString,
            research__service__pb2.ResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResearchStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/researchservice.v1.ResearchService/ResearchStream',
            research__service__pb2.ResearchRequest.SerializeToString,
            research__service__pb2.ResearchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
