# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: research_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'research_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16research_service.proto\x12\x12researchservice.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n\x0fResearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tsub_agent\x18\x02 \x01(\t\x12%\n\x1dmax_concurrent_research_units\x18\x03 \x01(\r\x12!\n\x19max_researcher_iterations\x18\x04 \x01(\r\x12)\n\x08metadata\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xa0\x01\n\rResearchEvent\x12\x39\n\nevent_type\x18\x01 \x01(\x0e\x32%.researchservice.v1.ResearchEventType\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xa5\x01\n\x10ResearchResponse\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0e\n\x06report\x18\x02 \x01(\t\x12\x15\n\rfinal_message\x18\x03 \x01(\t\x12)\n\x08metadata\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x30\n\x0c\x63ompleted_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\x98\x03\n\x11ResearchEventType\x12#\n\x1fRESEARCH_EVENT_TYPE_UNSPECIFIED\x10\x00\x12(\n$RESEARCH_EVENT_TYPE_RESEARCH_STARTED\x10\x01\x12!\n\x1dRESEARCH_EVENT_TYPE_TOOL_CALL\x10\x02\x12#\n\x1fRESEARCH_EVENT_TYPE_TOOL_RESULT\x10\x03\x12+\n\'RESEARCH_EVENT_TYPE_SUB_AGENT_DELEGATED\x10\x04\x12(\n$RESEARCH_EVENT_TYPE_SUB_AGENT_RESULT\x10\x05\x12 \n\x1cRESEARCH_EVENT_TYPE_PROGRESS\x10\x06\x12(\n$RESEARCH_EVENT_TYPE_REPORT_AVAILABLE\x10\x07\x12*\n&RESEARCH_EVENT_TYPE_RESEARCH_COMPLETED\x10\x08\x12\x1d\n\x19RESEARCH_EVENT_TYPE_ERROR\x10\t2\xc4\x01\n\x0fResearchService\x12U\n\x08Research\x12#.researchservice.v1.ResearchRequest\x1a$.researchservice.v1.ResearchResponse\x12Z\n\x0eResearchStream\x12#.researchservice.v1.ResearchRequest\x1a!.researchservice.v1.ResearchEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'research_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESEARCHEVENTTYPE']._serialized_start=612
  _globals['_RESEARCHEVENTTYPE']._serialized_end=1020
  _globals['_RESEARCHREQUEST']._serialized_start=110
  _globals['_RESEARCHREQUEST']._serialized_end=278
  _globals['_RESEARCHEVENT']._serialized_start=281
  _globals['_RESEARCHEVENT']._serialized_end=441
  _globals['_RESEARCHRESPONSE']._serialized_start=444
  _globals['_RESEARCHRESPONSE']._serialized_end=609
  _globals['_RESEARCHSERVICE']._serialized_start=1023
  _globals['_RESEARCHSERVICE']._serialized_end=1219
# @@protoc_insertion_point(module_scope)
